
exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('image_list').del()
    .then(function () {
      // Inserts seed entries
      return knex('image_list').insert([
        {post_id: 1,  images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/1585854567shelf1.png'},
        {post_id: 1,  images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/1585854567shelf2.png'},
        {post_id: 1,  images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/1585854567shelf3.png'},
        {post_id: 2,  images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/brush1.jpg'},
        {post_id: 2,  images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/brush2.jpg'},
        {post_id: 2,  images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/brush3.jpg'},
        {post_id: 3, images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/iphone_1.jpeg' },
        {post_id: 3, images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/iphone_2.jpeg' },
        {post_id: 3, images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/iphone_3.jpeg' },
        {post_id: 4, images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/sofa1.jpeg' },
        {post_id: 4, images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/sofa2.jpeg' },
        {post_id: 5,  images_link: 'https://craiglist2.s3.ca-central-1.amazonaws.com/sofaset_1.jpeg'},
        {post_id: 5,  images_link: 'https://craiglist2.s3.ca-central-1.amazonaws.com/sofaset_2.jpeg'},
        {post_id: 5,  images_link: 'https://craiglist2.s3.ca-central-1.amazonaws.com/sofaset_3.jpeg'},
        { post_id: 6, images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/macbook_1.jpeg' },
        { post_id: 6, images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/macbook_2.jpeg' },
        { post_id: 6, images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/macbook_3.jpeg' },
        {post_id: 7,  images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/1585547282sony-tv-65-1.jpg'},
        {post_id: 7,  images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/1585547282sony-tv-65-2.png'},
        {post_id: 7,  images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/1585547282sony-tv-65-3.png'},
        {post_id: 7,  images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/1585547282sony-tv-65-4.png'},
        {post_id: 8,  images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/backpack1.jpeg'},
        {post_id: 8,  images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/backpack2.jpeg'},
        {post_id: 8,  images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/backpack3.jpeg'},
        {post_id: 9,  images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/backpack6.jpeg'},
        {post_id: 9,  images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/backpack7.jpeg'},
        {post_id: 9,  images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/backpack8.jpeg'},
        {post_id: 10, images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/backpack4.jpeg'},
        {post_id: 10, images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/backpack5.jpeg'},
        {post_id: 11, images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/dell_lp1.jpeg'},
        {post_id: 11, images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/dell_lp2.jpeg'},
        {post_id: 11, images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/dell_lp3.jpeg'},
        {post_id: 11, images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/dell_lp4.jpeg'},
        {post_id: 12, images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/guitar1.jpeg'},
        {post_id: 12, images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/guitar2.jpeg'},
        {post_id: 12, images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/guitar3.jpeg'},
        {post_id: 12, images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/guitar4.jpeg'},
        {post_id: 12, images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/guitar5.jpeg'},
        {post_id: 13, images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/musical_instrument1.jpeg'},
        {post_id: 13, images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/musical_instrument2.jpeg'},
        {post_id: 13, images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/musical_instrument3.jpeg'},
        {post_id: 13, images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/musical_instrument4.jpeg'},
        {post_id: 13, images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/musical_instrument5.jpeg'},
        {post_id: 13, images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/musical_instrument6.jpeg'},
        {post_id: 14, images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/new_iphone7_1.jpeg'},
        {post_id: 14, images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/new_iphone7_2.jpeg'},
        {post_id: 14, images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/new_iphone7_3.jpeg'},
        {post_id: 14, images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/new_iphone7_4.jpeg'},
        {post_id: 14, images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/new_iphone7_5.jpeg'},
        {post_id: 14, images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/new_iphone7_6.jpeg'},
        {post_id: 15, images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/1586419602xbox-4.png'},
        {post_id: 15, images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/1586419727xbox-2.png'},
        {post_id: 16, images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/1586449230xbox-2.png'},
        {post_id: 17, images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/1586449780xbox-2.png'},
        {post_id: 17, images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/1586449780xbox-3.png'},
        {post_id: 17, images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/1586449780xbox-1.png'},
        {post_id: 18, images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/1586451551apple.jpg'},
        {post_id: 19, images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/1586451766aggretsuko-photocopy.jpg'},
        {post_id: 20, images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/1586451775aggretsuko-photocopy.jpg'},
        {post_id: 21, images_link: 'http://craiglist2.s3-website.ca-central-1.amazonaws.com/300xAUTO/1586452922apple.jpg'}
      ]);
    });
};
